### PR TITLE
systemjs useage complete, es6 support, etc, with some follow ons for prod code

### PR DESCRIPTION
**Pull request by mattkime**
check the readme for new build instructions

motivation for this
- es6 support with sourcemaps
- better dependency management

rough edges 
- more xhr requests than necessary in some situations
- more complex build process

there were some whitespace changes diff looks better with them hidden - https://github.com/jblotus/Try-Handlebars.js/pull/40/files?w=1

### CODE REVIEW

**Comment by mattkime** [comment]
i'm not sure why this is reporting as conflicting. looks like it should merge fine, give it a try

**Comment by jblotus** [comment]
this is pretty cool man.

re: build process - the build process is already kind of complicated from my perspective BUT if it makes it easier to add useful features then i'm all for it.

 I do enjoy es6 after using ember for a few weeks and systemjs seems like the logical es6 style module loader / package manager to use from what i've read.

i must admit that I don't 100% grok all the crazy modern web UI stuff going these days on so please bear with me =].  thank you for pushing this project forward.

**Comment by jblotus** [comment]
i'll need some time to get this merged and deployed, I don't want to mess it up.

**Comment by mattkime** [comment]
i see this as an intermediate step to removing content (examples) from script tags and into modules. the es6 template strings look really useful for that. 

it took me a bit of time to wrap my head around this stuff, feel free to ask questions

**Comment by jblotus** [comment]
hmm i just tried to merge manually but i wasn't sure of how to resolve the conflicts accurately. can you merge an updated master into your systemjs branch? it should create merge conflicts you can fix.

**Comment by mattkime** [comment]
i believe i fixed the issue. if pulling doesn't work and you're seeing the same conflict i am, just grab my systemjs branch version of the file.

**Comment by jblotus** [comment]
this has been deployed - hopefully intact =] - i ran through it a bit and didn't notice any issues. would you mind testing the live site to see if it's working as intended when you get a chance?

**Comment by mattkime** [comment]
looks good to me!

**Pull request merged**
