### PR TITLE
first pass on responsive refactor

### PR DESCRIPTION
**Pull request by mattkime**
This still needs some cleanup but i wanted to get your thoughts - 

- pulling in https://github.com/meetup/sassquatch2 - mainly for good breakpoints and a couple of other simple tools. its overkill but its easy

- flattened out the examples so they fit into a dropdown. i'll expand on these in the future.

todo for initial responsive pass 

- needs some style improvements
- remove style attrs from html

(not ready to be merged)

### CODE REVIEW

**Comment by jblotus** [comment]
sorry for the delay, been super busy. i'll pull this down tonight and take a look. thanks so much for your contributions!

**Comment by jblotus** [comment]
I'm struggling to build this right now. I installed the dev packages but I'm having an issue with sass 

[vagrant@localhost tryhbs]$ grunt sass
Running "sass:main" (sass) task
Warning: 
You need to have Ruby and Sass installed and in your PATH for this task to work.
More info: https://github.com/gruntjs/grunt-contrib-sass
 Use --force to continue.

is there a way you can build this put this up on one of those cloud ide services (cloud9, nitrous, etc) so we can take a look?

**Comment by jblotus** [comment]
nvm, didn't realize i needed ruby and sass installed as well. i guess it said so right in the error message.

**Comment by jblotus** [comment]
getting some other errors.

[vagrant@localhost tryhbs]$ /usr/lib/node_modules/bower/bin/bower install     
bower cached        git://github.com/meetup/sassquatch2.git#0.19.26
bower validate      0.19.26 against git://github.com/meetup/sassquatch2.git#~0.19.15
bower cached        git://github.com/meetup/meetup-swatches.git#1.1.0
bower validate      1.1.0 against git://github.com/meetup/meetup-swatches.git#>0.6.0
bower cached        git://github.com/thoughtbot/bourbon.git#4.1.0
bower validate      4.1.0 against git://github.com/thoughtbot/bourbon.git#4.1.0
bower install       sassquatch2#0.19.26
bower install       meetup-swatches#1.1.0
bower install       bourbon#4.1.0
bower UNKNOWN       UNKNOWN, open '/home/tryhbs/bower_components/sassquatch2/docs/build/sass_utils_|_functions.html'

Stack trace:
Error: UNKNOWN, open '/home/tryhbs/bower_components/sassquatch2/docs/build/sass_utils_|_functions.html'

Console trace:
Error
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:788:41)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.10.36
OS: Linux 2.6.32-504.el6.x86_64 x64
[vagrant@localhost tryhbs]$ cat package.json 
{
  "name": "Try-Handlebars.js",
  "version": "0.1.0",
  "description": "Try handlebars.js in the browser",
  "main": "Gruntfile.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/jblotus/Try-Handlebars.js.git"
  },
  "author": "Matt Kime <matt@mattki.me> (http://mattki.me)",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/jblotus/Try-Handlebars.js/issues"
  },
  "homepage": "https://github.com/jblotus/Try-Handlebars.js",
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-contrib-sass": "^0.9.2",
    "jit-grunt": "^0.9.1"
  },
  "scripts": {
    "install" : "bower install"
  }
}

**Comment by jblotus** [comment]
[vagrant@localhost tryhbs]$ grunt sass
Running "sass:main" (sass) task
Error: File to import not found or unreadable: ../bower_components/sassquatch2/sass/sassquatch.
        on line 1 of sass/main.scss
  Use --trace for backtrace.
Warning: Exited with error code 65 Use --force to continue.

Aborted due to warnings.

**Comment by mattkime** [comment]
ug, the downside of dependencies.

it looks like its failing to import sassquatch2. i'll take a look on my machine.

thanks,

**Comment by jblotus** [comment]
no prob. i'll be able to resume looking at this later tonight maybe tomorrow ( at work right now =] )

**Comment by jblotus** [comment]
also I just gave you collab status on this repo. Feel free to create a responsive branch here.

**Comment by mattkime** [comment]
looks like you were calling bower via its absolute path. i wonder if thats causing problems - it looks like its trying to find components relative to the user directory rather than the repo. at least thats my first guess.

i haven't tried cloud9 or nitrous but might to move things along. have a preference? have advice on getting started?

its my goal to get this to the point where i can make progress by giving this 10 min/day. i guess getting started is frequently the hard part.

**Comment by mattkime** [comment]
http://mattkime.github.io/

**Comment by jblotus** [comment]
i just checked it out...looks promising, the grid works great. we should get the existing colors, font style in there i think. i'd like to improve or distinguish the preview window a bit and perhaps set some sort of max width on the compile button.

i'll go ahead and set up a site on codio and try to get this up there.

**Comment by jblotus** [comment]
can you do me a favor and reissue this pull request against jblotus/responsive instead of jblotus/master?

**Comment by jblotus** [comment]
create an account on https://codio.com, tell me your username and i'll give you write access to the workspace (this will enable you to install packages, commit, etc)

https://codio.com/jblotus/tryhandlebars-js

**Comment by mattkime** [comment]
my username is mattkime

**Pull request closed without merging**
