### PR TITLE
Updated to handlebars 3.0.3

### PR DESCRIPTION
**Pull request by alexwebgr**
hi james 

i found your tool the other day as i was reading about handlebars and i noticed it was using an older version of handlebars so i had a look at the github repo and decided to fork it 
I updated all the libraries i also added bower and grunt to make dependencies easier to handle from now 
i also refactored the code under js/script.js a little bit 

have a look and let me know what you think 
i hope you accept my pull request and please let me know if you have any questions or need anything else 

best regards
alex

ref
https://github.com/jblotus/Try-Handlebars.js/issues/15

### CODE REVIEW

**Comment by jblotus** [comment]
really great work. i'll try to work on merging and deploying this soon! thanks a lot.

**Comment by alexwebgr** [comment]
good to hear you like it !
unfortunately i couldn't find suitable bower packages for modernizr and JSONPath, so modernizr still resides under /js/libs folder and JSONPath only exists as a node module 

alex

**Comment by jblotus** [comment]
just wanted to give a quick update. i plan on merging this but i need to get a new vps set up for tryhandlebarsjs.com before i can install node, bower, etc. before i can deploy.

**Comment by alexwebgr** [comment]
Looking good!!

**Pull request merged**
